users: 
- name: denis
  full_name: Denis
  passwd: $6$rounds=2048$bcJL4EP7s0mN1r$8DbXghzWXeUSV/8DoIv3FWilun706.DLveBsynpY93RDtBGSw/GfbXv4LtEKkhz9GyKAX4BWLYJA.vDqA1JPY1
  pub_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC8s38Km82OBm40s8/zF4gLeBt7UJDtoyL1nxAPDKlVZ7V/sf9+PXXSymGowfvRGuqjR9pcVYIEOCHcp+DqN8JirenAoBYbLtPdFL7lt6Y+J5YTfqxpFmjhirVdyp8blZYpHKav6De7mG4iAmmm/5qGcXgh4R0Q06vygK20NS2+lllfBlieXQupmKH2FEhEqmC9PrIe48Icmc8DFtQFZ70OX6enfiOBrDOHcJWhwtN6gU9GrlUIaf7JIe1TrCKsPhUawzeqW6n9xB+1vSYVBY3LSY9Dnyepa/TfEWjCRScugZGe/05zHMqAf0yFAoRHiz8eCWnxKSH6qjy8gRC55Vun3Qf7mCXi5xlYqdoMlfxyQS3DLLERTUuwqVqjP38YLNZt9zL94HaRwe5vLqWPL3cTJD7V+odTQhIYKHRsKScKZQiqc1Igk4IbZL/U4SLDA1NIHPVeMdCdp6Lv6nqrYLZ8EFitiw7Z5nEI1KTk1U9MpztkbZtOJQ7uc8on4DNF15s= disa@boeinghost

network_name: br10
virtual_machines:
- name: master1
  cpu: 2
  mem: 2048
  disk: 20G
  bridge: "{{ network_name }}"
  net:
    ip: 192.168.30.2/24
    gateway: 192.168.30.1
    nameservers: "[192.168.0.1]"

- name: master2
  cpu: 2
  mem: 2048
  disk: 20G
  bridge: "{{ network_name }}"
  net:
    ip: 192.168.30.3/24
    gateway: 192.168.30.1
    nameservers: "[192.168.0.1]"

- name: master3
  cpu: 2
  mem: 2048
  disk: 20G
  bridge: "{{ network_name }}"
  net:
    ip: 192.168.30.4/24
    gateway: 192.168.30.1
    nameservers: "[192.168.0.1]"

- name: worker1
  cpu: 2
  mem: 2048
  disk: 20G
  bridge: "{{ network_name }}"
  net:
    ip: 192.168.30.5/24
    gateway: 192.168.30.1
    nameservers: "[192.168.0.1]"

- name: worker2
  cpu: 2
  mem: 2048
  disk: 20G
  bridge: "{{ network_name }}"
  net:
    ip: 192.168.30.6/24
    gateway: 192.168.30.1
    nameservers: "[192.168.0.1]"

- name: worker3
  cpu: 2
  mem: 2048
  disk: 20G
  bridge: "{{ network_name }}"
  net:
    ip: 192.168.30.7/24
    gateway: 192.168.30.1
    nameservers: "[192.168.0.1]"

- name: haproxy
  cpu: 2
  mem: 2048
  disk: 20G
  bridge: "{{ network_name }}"
  net:
    ip: 192.168.30.8/24
    gateway: 192.168.30.1
    nameservers: "[192.168.0.1]"