---
- name: KVM and QEMU System components
  apt:
    name:
      - qemu-kvm
      - libvirt-daemon-system
      - libvirt-clients
      - python3-libvirt
      - python3-lxml
      - bridge-utils
      - cloud-image-utils
      - virtinst

- name: Libvirtd systemd service
  service:
    name: libvirtd
    enabled: true
    state: started

- name: qemu images directory
  file:
    state: directory
    path: /virt/images

- name: Check Ubuntu 20.04 cloud image
  uri:
    url: https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img
    method: HEAD
  register: cloudimg_http_stat
  check_mode: false

- name: Check local cloud image
  stat:
    path: /virt/images/focal-server-cloudimg-amd64.img
    get_checksum: false
  register: cloudimg_local_stat

- name: Update Ubuntu 20.04 cloud image
  get_url:
    url: https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img
    dest: /virt/images/focal-server-cloudimg-amd64.img
  when: not cloudimg_local_stat.stat.exists or
        cloudimg_local_stat.stat.size != cloudimg_http_stat.content_length
  register: cloudimg_local_updated

- name: Convert cloud image qcow format
  shell:
    chdir: /virt/images/
    cmd: qemu-img convert -f qcow2 focal-server-cloudimg-amd64.img focal-server-cloudimg-amd64.qcow2
    creates: /virt/images/focal-server-cloudimg-amd64.qcow2
  when: cloudimg_local_updated.changed|bool

- name: Virtual machine directory
  file:
    path: /virt/vms
    state: directory
    owner: root
    group: root
    mode: 0755
