---
- name: Update apt package cache
  apt:
    update_cache: yes

- name: install collection timezone
  shell: ansible-galaxy collection install community.general

- name: Setup KVM platform
  include_tasks: "{{ item }}"
  loop:
    - install_kvm.yml