---
- name: Set timezone
  ansible.builtin.timezone:
    name: "Asia/Yekaterinburg"

- name: Install HAProxy
  apt:
    name: haproxy
    state: present

- name: Copy HAProxy configuration file
  template:
    src: templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg

- name: Restart HAProxy
  service:
    name: haproxy
    state: restarted