- name: Prepare host node and create vm's
  become: yes
  hosts: host_machine
  roles:
    - roles/qemu

- name: Generate Certs
  become: yes
  hosts: host_machine
  roles:
    - roles/certs_gen

- name: Preparation haproxy node
  become: yes
  hosts: haproxy
  roles:
    - roles/haproxy

- name: Preparation master and work nodes
  become: yes
  hosts: masters, workers
  roles:
    - roles/common
    
- name: Install k8s and create etcd cluster
  become: yes
  hosts: masters
  roles:
    - roles/master_nodes